path_to_fauna = '../fauna'

# Use default configuration values. Override with Snakemake's --configfile/--config options.
configfile: "defaults/config.yaml"

wildcard_constraints:
    segment = "|".join(config["segments"])

rule all:
    # As of 2024-05-16 the default ingest only ingests data from fauna
    input:
        sequences=expand("fauna/results/sequences_{segment}.fasta", segment=config["segments"]),
        metadata="fauna/results/metadata.tsv",

rule upload_all:
    # As of 2024-05-16 the default upload only uploads data from fauna
    input:
        sequences=expand("fauna/s3/sequences_{segment}.done", segment=config["segments"]),
        metadata="fauna/s3/metadata.done",

include: "rules/upload_from_fauna.smk"
include: "rules/ingest_andersen_lab.smk"
