# Use default configuration values. Override with Snakemake's --configfile/--config options.
configfile: "defaults/config.yaml"

SUPPORTED_DATA_SOURCES = ["ncbi", "andersen-lab", "joined-ncbi"]

wildcard_constraints:
    segment = "|".join(config["segments"]),
    data_source = "|".join(SUPPORTED_DATA_SOURCES)

rule all:
    # As of 2026-01-28 the default ingest is for joined-ncbi
    input:
        sequences=expand("joined-ncbi/results/sequences_{segment}.fasta", segment=config["segments"]),
        metadata="joined-ncbi/results/metadata.tsv",

rule upload_all:
    # As of 2026-01-28 the default upload is for joined-ncbi
    input:
        sequences=expand("joined-ncbi/s3/sequences_{segment}.done", segment=config["segments"]),
        metadata="joined-ncbi/s3/metadata.done",

include: "rules/merge_segment_metadata.smk"
include: "rules/genoflu.smk"
include: "rules/upload_to_s3.smk"

# Allow users to import custom rules provided via the config.
if "custom_rules" in config:
    for rule_file in config["custom_rules"]:

        include: rule_file
