path_to_fauna = '../fauna'
config["s3_dst"] = "s3://nextstrain-data-private/files/workflows/avian-flu"
config["segments"] = ["pb2", "pb1", "pa", "ha","np", "na", "mp", "ns"]

wildcard_constraints:
    segment = "|".join(config["segments"])

rule all:
    # As of 2024-05-16 the default ingest only ingests data from fauna
    input:
        sequences=expand("fauna/results/sequences_{segment}.fasta", segment=config["segments"]),
        metadata="fauna/results/metadata.tsv",

rule upload_all:
    # As of 2024-05-16 the default upload only uploads data from fauna
    input:
        sequences=expand("fauna/s3/sequences_{segment}.done", segment=config["segments"]),
        metadata="fauna/s3/metadata.done",

include: "rules/upload_from_fauna.smk"
include: "rules/ingest_andersen_lab.smk"
