# Config for the NCBI ingest workflow

custom_rules:
  - "build-configs/ncbi/Snakefile"

# NCBI taxon id for "Influenza A virus", which are then further
# labeled with `serotype` (e.g. H5N1)
ncbi_taxon_id: "11320"

# Parameters for the NCBI Virus API call to get the metadata of sequences
# with additional fields: strain, serotype, segment
ncbi_virus_min_collection_date: "2023-12-31"
ncbi_virus_filters:
  - '{!tag=Region_s}Region_s:("North America")'
  - 'Serotype_s:("H5N1")'

# Matching segment names used in fauna to the numeric segments returned by NCBI
ncbi_segments:
  pb2: "1"
  pb1: "2"
  pa: "3"
  ha: "4"
  np: "5"
  na: "6"
  mp: "7"
  ns: "8"

# Config parameters related to the curate pipeline
curate:
  # URL pointed to public generalized geolocation rules
  # For the Nextstrain team, this is currently
  # "https://raw.githubusercontent.com/nextstrain/ncov-ingest/master/source-data/gisaid_geoLocationRules.tsv"
  geolocation_rules_url: "https://raw.githubusercontent.com/nextstrain/ncov-ingest/master/source-data/gisaid_geoLocationRules.tsv"
  # The path to the local geolocation rules within the pathogen repo
  # The path should be relative to the ingest directory.
  local_geolocation_rules: "defaults/geolocation_rules.tsv"
  # List of field names to change where the key is the original field name and the value is the new field name
  # The original field names should match the ncbi_datasets_fields provided above.
  # This is the first step in the pipeline, so any references to field names in the configs below should use the new field names
  field_map:
    accession: genbank_accession
    accession_version: genbank_accession_version
    sourcedb: database
    sra-accs: sra_accessions
    strain: strain
    segment: segment
    serotype: subtype
    isolate-lineage: isolate
    geo-region: region
    geo-location: location
    isolate-collection-date: date
    release-date: date_released
    update-date: date_updated
    length: length
    host-name: host
    isolate-lineage-source: sample_type
    biosample-acc: biosample_accessions
    submitter-names: authors
    submitter-affiliation: submitting_lab
    # These columns are added to match fauna outputs
    isolate_id: isolate_id
    virus: virus
    domestic_status: domestic_status
    originating_lab: originating_lab
    PMID: PMID
    gisaid_clade: gisaid_clade
    h5_clade: h5_clade

  # Standardized strain name regex
  # Currently accepts any characters because we do not have a clear standard for strain names across pathogens
  strain_regex: "^.+$"
  # Back up strain name field to use if "strain" doesn"t match regex above
  strain_backup_fields: ["isolate", "genbank_accession"]
  # List of date fields to standardize to ISO format YYYY-MM-DD
  date_fields: ["date", "date_released", "date_updated"]
  # List of expected date formats that are present in the date fields provided above
  # These date formats should use directives expected by datetime
  # See https://docs.python.org/3.9/library/datetime.html#strftime-and-strptime-format-codes
  expected_date_formats: ["%Y", "%Y-%m", "%Y-%m-%d", "%Y-%m-%dT%H:%M:%SZ"]
  titlecase:
    # List of string fields to titlecase
    fields: ["region", "country", "division", "location"]
    # List of abbreviations not cast to titlecase, keeps uppercase
    abbreviations: ["USA"]
    # Articles that should not be cast to titlecase
    articles: [
      "and", "d", "de", "del", "des", "di", "do", "en", "l", "la", "las", "le",
      "los", "nad", "of", "op", "sur", "the", "y"
    ]
  # Metadata field that contains the list of authors associated with the sequence
  authors_field: "authors"
  # Default value to use if the authors field is empty
  authors_default_value: "?"
  # Name to use for the generated abbreviated authors field
  abbr_authors_field: "abbr_authors"
  # Path to the host map file
  # The path should be relative to the ingest directory
  host_map: "build-configs/ncbi/defaults/host-map.tsv"
  # Path to the manual annotations file
  # The path should be relative to the ingest directory
  annotations: "build-configs/ncbi/defaults/annotations.tsv"
  # The ID field in the metadata to use to merge the manual annotations
  annotations_id: "strain"
  # The ID field in the metadata to use as the sequence id in the output FASTA file
  output_id_field: "strain"
  # The field in the NDJSON record that contains the actual genomic sequence
  output_sequence_field: "sequence"
  # The list of metadata columns to keep in the final output of the curation pipeline.
  # Explicitly matching the metadata columns output by fauna
  metadata_columns:
  - strain
  - virus
  - isolate_id
  - date
  - region
  - country
  - division
  - location
  - host
  - domestic_status
  - subtype
  - originating_lab
  - submitting_lab
  - authors
  - PMID
  - gisaid_clade
  - h5_clade
  - genbank_accession
  - sra_accessions
  - date_released

s3_dst:
  ncbi: s3://nextstrain-data/files/workflows/avian-flu/h5n1/ncbi
  andersen-lab: s3://nextstrain-data/files/workflows/avian-flu/h5n1/andersen-lab
  joined-ncbi: s3://nextstrain-data/files/workflows/avian-flu/h5n1

cloudfront_domain: data.nextstrain.org

join_ncbi_andersen:
  match_field: sra_accessions
  source_column_name: data_source
  ncbi_source: genbank
  andersen_source: sra-via-andersen-lab
  dedup_column: strain
