"""
This is the NCBI ingest Snakefile that orchestrates the NCBI ingest
workflow and defines its default outputs.
"""
# Use default configuration values. Override with Snakemake's --configfile/--config options.
configfile: "build-configs/ncbi/defaults/config.yaml"

# Sanity check that the requested segments match our ncbi_segments map
assert all(segment in config["ncbi_segments"].keys() for segment in config["segments"])


rule ingest_ncbi:
    input:
        expand([
            "ncbi/results/sequences_{segment}.fasta",
        ], segment=config["segments"]),
        "ncbi/results/metadata.tsv",


rule ingest_andersen_lab:
    input:
        expand([
            "andersen-lab/results/sequences_{segment}.fasta",
        ], segment=config["segments"]),
        "andersen-lab/results/metadata.tsv",


# Include file paths are relative this Snakefile
include: "rules/ingest_andersen_lab.smk"
include: "rules/fetch_from_ncbi.smk"
include: "rules/curate.smk"
