"""
This is the NCBI ingest Snakefile that orchestrates the NCBI ingest
workflow and defines its default outputs.
"""
# Use default configuration values. Override with Snakemake's --configfile/--config options.
configfile: "defaults/config.yaml"

rule all:
    input:
        "results/sequences.fasta",
        "results/metadata.tsv",

include: "rules/fetch_from_ncbi.smk"
include: "rules/curate.smk"
