#### Parameters which define which builds to produce via this config ###
builds:
  h5n1-cattle-outbreak: ''

segments:
  - genome
  - pb2
  - pb1
  - pa
  - ha
  - np
  - na
  - mp
  - ns


#### Parameters which define the input source ####
s3_src:
  name: ncbi
  metadata: s3://nextstrain-data/files/workflows/avian-flu/h5n1/metadata.tsv.zst
  sequences: s3://nextstrain-data/files/workflows/avian-flu/h5n1/{segment}/sequences.fasta.zst
local_ingest: false
# P.S. To use local ingest files, comment out s3_src and change to local_ingest: joined-ncbi (e.g.)


#### Parameters which control large overarching aspects of the build
# Set a high target_sequences_per_tree to capture all circulating strains, as they will be pruned down
# as part of the workflow
target_sequences_per_tree: 10_000


#### Config files ####

reference: config/h5n1/reference_h5n1_{segment}.gb  # use H5N1 references
genome_reference: config/{subtype}/h5_cattle_genome_root.gb
auspice_config: config/{subtype}/auspice_config_{subtype}.json
colors: config/h5n1/colors_h5n1.tsv # use H5N1 colors
lat_longs: config/h5n1/lat_longs_h5n1.tsv # use H5N1 lat-longs
include_strains: config/{subtype}/include_strains_{subtype}.txt
# use cattle-outbreak specific dropped strains for segment + genome trees
dropped_strains: config/{subtype}/dropped_strains_{subtype}.txt
clades_file: clade-labeling/h5n1-clades.tsv # use H5N1 clades
description: config/{subtype}/description_{subtype}.md


#### Rule-specific parameters ####
filter:
  min_length:
    "*/pb2/*": 2100 # Note: could use "h5n1-cattle-outbreak/pb2/default: 2100" if desired
    "*/pb1/*": 2100
    "*/pa/*": 2000
    "*/ha/*": 1600
    "*/np/*": 1400
    "*/na/*": 1270
    "*/mp/*": 900
    "*/ns/*": 800

  min_date: 2024

  group_by: false # no grouping during filter

  exclude_where:
    host=laboratoryderived host=ferret host=unknown host=other host=host gisaid_clade=3C.2


refine:
  coalescent: const
  date_inference: marginal

  clock_filter_iqd:
    "*/genome/*": 3
    "*/*/*": false

  root: false

  # For the genome only we use the closest outgroup as the root
  # P.S. Make sure this strain is force included via augur filter --include
  # (This isn't needed for the segment builds as we include a large enough time span to root via the clock)
  genome_root: A/skunk/NewMexico/24-006483-001/2024

  segment_lengths:
    "*/pb2/*": 2341
    "*/pb1/*": 2341
    "*/pa/*": 2233
    "*/ha/*": 1565
    "*/np/*": 1400
    "*/na/*": 1458
    "*/mp/*": 1027
    "*/ns/*": 865

  clock_rates:
    # The rates for the 8 segments are taken from the GISAID H5N1/2y config
    "*/pb2/*": [0.00287, &clock_std_dev 0.00211]
    "*/pb1/*": [0.00264, *clock_std_dev]
    "*/pa/*": [0.00248, *clock_std_dev]
    "*/ha/*": [0.00455, *clock_std_dev]
    "*/np/*": [0.00252, *clock_std_dev]
    "*/na/*": [0.00349, *clock_std_dev]
    "*/mp/*": [0.00191, *clock_std_dev]
    "*/ns/*": [0.00249, *clock_std_dev]
    # NOTE:
    # the genome clock rate is calculated by a function in the snakemake pipeline
    # using the segment rates weighted by their lengths

ancestral:
  inference: joint
  root_seq: false
  genome_root_seq: config/h5n1-cattle-outbreak/h5_cattle_genome_root.gb

traits:
  columns:
    "*/genome/*": division
    "*/*/*": region country  # segment builds are the same as GISAID H5N1 builds

  sampling_bias_correction:
    "*/genome/*": 5
    "*/*/*": false

  confidence: true

export:
  title:
    "*/genome/*": Full genome analysis of the ongoing influenza A/H5N1 cattle outbreak in North America
    "*/*/*": Ongoing influenza A/H5N1 cattle outbreak in North America ({segment} segment)
