name: Phylogenetic NCBI

defaults:
  run:
    # This is the same as GitHub Action's `bash` keyword as of 20 June 2023:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    #
    # Completely spelling it out here so that GitHub can't change it out from under us
    # and we don't have to refer to the docs to know the expected behavior.
    shell: bash --noprofile --norc -eo pipefail {0}

on:
  workflow_dispatch:

jobs:
  phylogenetic:
    permissions:
      id-token: write
    uses: nextstrain/.github/.github/workflows/pathogen-repo-build.yaml@master
    secrets: inherit
    with:
      runtime: docker
      run: |
        nextstrain build
          . \
            deploy_all \
            --snakefile Snakefile.genome \
            --config s3_src=s3://nextstrain-data/files/workflows/avian-flu/h5n1
      artifact-name: phylogenetic-full-genome-build-output
